name: Deploy Frontend To EC2

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/la-front-end
            git pull origin dev
            rm -rf build
            npm install
            npm run build
            sudo fuser -k -n tcp 3000 || true
            npx serve -s build -l 3000 > ./front_output.log 2>&1 &
